### PR TITLE
use ps2sdk udptty instead of internal

### PR DESCRIPTION
**Pull request by bignaux**
this main step to remove OPL/modules/debug/ps2link/ and use this repository as a component.

### CODE REVIEW

**Comment by AKuHAK** [comment]
Does it change something from user experience?

**Comment by bignaux** [comment]
I try to not make any change on UX for this first step. I checked, we could remove OPL/modules/debug/ioptrap safely in same time. I just use meld and try to report stuff from ps2link opl ... nothing new here.

**Comment by fjtrujy** [comment]
Rebase your branch the CI has been fixed and now it shouldn’t skip the compilation

**Comment by bignaux** [comment]
done.

**Comment by bignaux** [comment]
I let some ps2link.c: extern int ttyMount(void); but this function doesn't exist anymore ( now _start )
it should probably be clean in ps2sdk: iop/fs/fakehost/src/fakehost.c

**Comment by fjtrujy** [comment]
> I let some ps2link.c: extern int ttyMount(void); but this function doesn't exist anymore ( now _start )
> it should probably be clean in ps2sdk: iop/fs/fakehost/src/fakehost.c

Could you please make this PR to PS2SDK as well? We will merge them y the proper order

**Comment by bignaux** [comment]
i'd prefer not do that now, and i don't know enough ps2sdk to commit on it for now.

**Comment by rickgaiser** [comment]
Thanks @bignaux this cleans up 1 copy of udptty. Can you do the same with the OPL version?
So the only udptty left will be the one in ps2sdk.

**Comment by bignaux** [comment]
yes, we could remove OPL/modules/debug/udptty-ingame also... when i finished stuff to be able to use ps2link as a component.

**Comment by bignaux** [comment]
done.

**Pull request merged**
